//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekNumber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeekNumber.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeekNumber by Voltura AB
        ///
        ///Copyright © Voltura AB 2018-2021.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WeekNumber.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationLog.
        /// </summary>
        internal static string ApplicationLog {
            get {
                return ResourceManager.GetString("ApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application log.
        /// </summary>
        internal static string ApplicationLogMenu {
            get {
                return ResourceManager.GetString("ApplicationLogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoUpdate.
        /// </summary>
        internal static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update automatically.
        /// </summary>
        internal static string AutoUpdateMenu {
            get {
                return ResourceManager.GetString("AutoUpdateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version:.
        /// </summary>
        internal static string AvailableVersion {
            get {
                return ResourceManager.GetString("AvailableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarSettingsMenu {
            get {
                return ResourceManager.GetString("CalendarSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar week rule.
        /// </summary>
        internal static string CalendarWeekRuleMenu {
            get {
                return ResourceManager.GetString("CalendarWeekRuleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if you can navigate via a web browser to this address:.
        /// </summary>
        internal static string CheckBrowserNavigation {
            get {
                return ResourceManager.GetString("CheckBrowserNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually check for newer version here:.
        /// </summary>
        internal static string CheckForNewVersionHere {
            get {
                return ResourceManager.GetString("CheckForNewVersionHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updated version.
        /// </summary>
        internal static string CheckForNewVersionMenu {
            get {
                return ResourceManager.GetString("CheckForNewVersionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get week number for date....
        /// </summary>
        internal static string CheckWeekForDateMenu {
            get {
                return ResourceManager.GetString("CheckWeekForDateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this application and manually run.
        /// </summary>
        internal static string CloseAppAndManuallyRun {
            get {
                return ResourceManager.GetString("CloseAppAndManuallyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon colors.
        /// </summary>
        internal static string ColorsMenu {
            get {
                return ResourceManager.GetString("ColorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompositingQuality.
        /// </summary>
        internal static string CompositingQuality {
            get {
                return ResourceManager.GetString("CompositingQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assume Linear.
        /// </summary>
        internal static string CompositingQualityAssumeLinearMenu {
            get {
                return ResourceManager.GetString("CompositingQualityAssumeLinearMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string CompositingQualityDefaultMenu {
            get {
                return ResourceManager.GetString("CompositingQualityDefaultMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma Corrected.
        /// </summary>
        internal static string CompositingQualityGammaCorrectedMenu {
            get {
                return ResourceManager.GetString("CompositingQualityGammaCorrectedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality.
        /// </summary>
        internal static string CompositingQualityHighQualityMenu {
            get {
                return ResourceManager.GetString("CompositingQualityHighQualityMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Speed.
        /// </summary>
        internal static string CompositingQualityHighSpeedMenu {
            get {
                return ResourceManager.GetString("CompositingQualityHighSpeedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compositing Quality.
        /// </summary>
        internal static string CompositingQualityMenu {
            get {
                return ResourceManager.GetString("CompositingQualityMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayStartupNotification.
        /// </summary>
        internal static string DisplayStartupNotification {
            get {
                return ResourceManager.GetString("DisplayStartupNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display startup notification.
        /// </summary>
        internal static string DisplayStartupNotificationMenu {
            get {
                return ResourceManager.GetString("DisplayStartupNotificationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayWeekChangedNotification.
        /// </summary>
        internal static string DisplayWeekChangedNotification {
            get {
                return ResourceManager.GetString("DisplayWeekChangedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display new week notification.
        /// </summary>
        internal static string DisplayWeekChangedNotificationMenu {
            get {
                return ResourceManager.GetString("DisplayWeekChangedNotificationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install new version now?.
        /// </summary>
        internal static string DownloadAndInstallQuestion {
            get {
                return ResourceManager.GetString("DownloadAndInstallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishMenu {
            get {
                return ResourceManager.GetString("EnglishMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit WeekNumber.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings....
        /// </summary>
        internal static string ExportSettingsMenu {
            get {
                return ResourceManager.GetString("ExportSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download and run the installer automatically..
        /// </summary>
        internal static string FailedAutoInstall {
            get {
                return ResourceManager.GetString("FailedAutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update icon resolution..
        /// </summary>
        internal static string FailedToChangeIconResolution {
            get {
                return ResourceManager.GetString("FailedToChangeIconResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform version check, cannot find an active internet connection..
        /// </summary>
        internal static string FailedToCheckUpdateNoInternet {
            get {
                return ResourceManager.GetString("FailedToCheckUpdateNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download new version..
        /// </summary>
        internal static string FailedToDownloadNewVersion {
            get {
                return ResourceManager.GetString("FailedToDownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export settings!.
        /// </summary>
        internal static string FailedToExportSettings {
            get {
                return ResourceManager.GetString("FailedToExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import settings!.
        /// </summary>
        internal static string FailedToImportSettings {
            get {
                return ResourceManager.GetString("FailedToImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not inform Windows about change of taskbar icon size.
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToNotifyWindowsOfTaskbarIconSizeChange {
            get {
                return ResourceManager.GetString("FailedToNotifyWindowsOfTaskbarIconSizeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform version check..
        /// </summary>
        internal static string FailedToPerformVersionCheck {
            get {
                return ResourceManager.GetString("FailedToPerformVersionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set Icon. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToSetIcon {
            get {
                return ResourceManager.GetString("FailedToSetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start the installer automatically..
        /// </summary>
        internal static string FailedToStartInstaller {
            get {
                return ResourceManager.GetString("FailedToStartInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not calendar week rule setting. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateCalendarWeekRule {
            get {
                return ResourceManager.GetString("FailedToUpdateCalendarWeekRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update color..
        /// </summary>
        internal static string FailedToUpdateColor {
            get {
                return ResourceManager.GetString("FailedToUpdateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update first day of week setting.
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateDayOfWeek {
            get {
                return ResourceManager.GetString("FailedToUpdateDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update registry.
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateRegistry {
            get {
                return ResourceManager.GetString("FailedToUpdateRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day.
        /// </summary>
        internal static string FirstDayMenu {
            get {
                return ResourceManager.GetString("FirstDayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day Of Week.
        /// </summary>
        internal static string FirstDayOfWeekMenu {
            get {
                return ResourceManager.GetString("FirstDayOfWeekMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Four Day Week.
        /// </summary>
        internal static string FirstFourDayWeekMenu {
            get {
                return ResourceManager.GetString("FirstFourDayWeekMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Full Week.
        /// </summary>
        internal static string FirstFullWeekMenu {
            get {
                return ResourceManager.GetString("FirstFullWeekMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string FridayMenu {
            get {
                return ResourceManager.GetString("FridayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics settings.
        /// </summary>
        internal static string GraphicsSettingsMenu {
            get {
                return ResourceManager.GetString("GraphicsSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128x128.
        /// </summary>
        internal static string Icon128 {
            get {
                return ResourceManager.GetString("Icon128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16x16.
        /// </summary>
        internal static string Icon16 {
            get {
                return ResourceManager.GetString("Icon16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20x20.
        /// </summary>
        internal static string Icon20 {
            get {
                return ResourceManager.GetString("Icon20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24x24.
        /// </summary>
        internal static string Icon24 {
            get {
                return ResourceManager.GetString("Icon24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256x256.
        /// </summary>
        internal static string Icon256 {
            get {
                return ResourceManager.GetString("Icon256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32x32.
        /// </summary>
        internal static string Icon32 {
            get {
                return ResourceManager.GetString("Icon32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40x40.
        /// </summary>
        internal static string Icon40 {
            get {
                return ResourceManager.GetString("Icon40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48x48.
        /// </summary>
        internal static string Icon48 {
            get {
                return ResourceManager.GetString("Icon48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 512x512.
        /// </summary>
        internal static string Icon512 {
            get {
                return ResourceManager.GetString("Icon512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64x64.
        /// </summary>
        internal static string Icon64 {
            get {
                return ResourceManager.GetString("Icon64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconBackground.
        /// </summary>
        internal static string IconBackground {
            get {
                return ResourceManager.GetString("IconBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconBackgroundBlue.
        /// </summary>
        internal static string IconBackgroundBlue {
            get {
                return ResourceManager.GetString("IconBackgroundBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconBackgroundGreen.
        /// </summary>
        internal static string IconBackgroundGreen {
            get {
                return ResourceManager.GetString("IconBackgroundGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string IconBackgroundMenu {
            get {
                return ResourceManager.GetString("IconBackgroundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconBackgroundRed.
        /// </summary>
        internal static string IconBackgroundRed {
            get {
                return ResourceManager.GetString("IconBackgroundRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconForeground.
        /// </summary>
        internal static string IconForeground {
            get {
                return ResourceManager.GetString("IconForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconForegroundBlue.
        /// </summary>
        internal static string IconForegroundBlue {
            get {
                return ResourceManager.GetString("IconForegroundBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconForegroundGreen.
        /// </summary>
        internal static string IconForegroundGreen {
            get {
                return ResourceManager.GetString("IconForegroundGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string IconForegroundMenu {
            get {
                return ResourceManager.GetString("IconForegroundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconForegroundRed.
        /// </summary>
        internal static string IconForegroundRed {
            get {
                return ResourceManager.GetString("IconForegroundRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string IconMenu {
            get {
                return ResourceManager.GetString("IconMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconResolution.
        /// </summary>
        internal static string IconResolution {
            get {
                return ResourceManager.GetString("IconResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon resolution.
        /// </summary>
        internal static string IconResolutionMenu {
            get {
                return ResourceManager.GetString("IconResolutionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings....
        /// </summary>
        internal static string ImportSettingsMenu {
            get {
                return ResourceManager.GetString("ImportSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version:.
        /// </summary>
        internal static string InstalledVersion {
            get {
                return ResourceManager.GetString("InstalledVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterpolationMode.
        /// </summary>
        internal static string InterpolationMode {
            get {
                return ResourceManager.GetString("InterpolationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicubic.
        /// </summary>
        internal static string InterpolationModeBicubicMenu {
            get {
                return ResourceManager.GetString("InterpolationModeBicubicMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear.
        /// </summary>
        internal static string InterpolationModeBilinearMenu {
            get {
                return ResourceManager.GetString("InterpolationModeBilinearMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string InterpolationModeDefaultMenu {
            get {
                return ResourceManager.GetString("InterpolationModeDefaultMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string InterpolationModeHighMenu {
            get {
                return ResourceManager.GetString("InterpolationModeHighMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality Bicubic.
        /// </summary>
        internal static string InterpolationModeHighQualityBicubicMenu {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBicubicMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality Bilinear.
        /// </summary>
        internal static string InterpolationModeHighQualityBilinearMenu {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBilinearMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string InterpolationModeLowMenu {
            get {
                return ResourceManager.GetString("InterpolationModeLowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation Mode.
        /// </summary>
        internal static string InterpolationModeMenu {
            get {
                return ResourceManager.GetString("InterpolationModeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Neighbor.
        /// </summary>
        internal static string InterpolationModeNearestNeighborMenu {
            get {
                return ResourceManager.GetString("InterpolationModeNearestNeighborMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer checksum incorrect, could not install automatically..
        /// </summary>
        internal static string InvalidChecksumCouldNotAutoInstall {
            get {
                return ResourceManager.GetString("InvalidChecksumCouldNotAutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version!.
        /// </summary>
        internal static string LatestVersionInstalled {
            get {
                return ResourceManager.GetString("LatestVersionInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLogFileSizeInMB.
        /// </summary>
        internal static string MaxLogFileSizeInMB {
            get {
                return ResourceManager.GetString("MaxLogFileSizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string MondayMenu {
            get {
                return ResourceManager.GetString("MondayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version available!.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string NotificationsMenu {
            get {
                return ResourceManager.GetString("NotificationsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this function is not implemented yet..
        /// </summary>
        internal static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open application web page.
        /// </summary>
        internal static string OpenApplicationWebPageMenu {
            get {
                return ResourceManager.GetString("OpenApplicationWebPageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeekNumber by Voltura AB.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors reset.
        /// </summary>
        internal static string ResetColors {
            get {
                return ResourceManager.GetString("ResetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset colors.
        /// </summary>
        internal static string ResetColorsMenu {
            get {
                return ResourceManager.GetString("ResetColorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string SaturdayMenu {
            get {
                return ResourceManager.GetString("SaturdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save icon....
        /// </summary>
        internal static string SaveIconMenu {
            get {
                return ResourceManager.GetString("SaveIconMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select background color.
        /// </summary>
        internal static string SelectBackgroundColor {
            get {
                return ResourceManager.GetString("SelectBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select date
        ///to show week number.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select foreground color.
        /// </summary>
        internal static string SelectForegroundColor {
            get {
                return ResourceManager.GetString("SelectForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SeparatorMenu {
            get {
                return ResourceManager.GetString("SeparatorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings successfully exported!.
        /// </summary>
        internal static string SettingsExported {
            get {
                return ResourceManager.GetString("SettingsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings successfully imported!.
        /// </summary>
        internal static string SettingsImported {
            get {
                return ResourceManager.GetString("SettingsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowLog.
        /// </summary>
        internal static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show application log.
        /// </summary>
        internal static string ShowLogMenu {
            get {
                return ResourceManager.GetString("ShowLogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti Alias.
        /// </summary>
        internal static string SmoothingAntiAliasMenu {
            get {
                return ResourceManager.GetString("SmoothingAntiAliasMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmoothingMode.
        /// </summary>
        internal static string SmoothingMode {
            get {
                return ResourceManager.GetString("SmoothingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string SmoothingModeDefaultMenu {
            get {
                return ResourceManager.GetString("SmoothingModeDefaultMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Quality.
        /// </summary>
        internal static string SmoothingModeHighQualityMenu {
            get {
                return ResourceManager.GetString("SmoothingModeHighQualityMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Speed.
        /// </summary>
        internal static string SmoothingModeHighSpeedMenu {
            get {
                return ResourceManager.GetString("SmoothingModeHighSpeedMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing mode.
        /// </summary>
        internal static string SmoothingModeMenu {
            get {
                return ResourceManager.GetString("SmoothingModeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SmoothingModeNoneMenu {
            get {
                return ResourceManager.GetString("SmoothingModeNoneMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click on icon in the system 
        ///tray for features and settings.
        /// </summary>
        internal static string StartupMessageText {
            get {
                return ResourceManager.GetString("StartupMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartWithWindows.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string StartWithWindowsMenu {
            get {
                return ResourceManager.GetString("StartWithWindowsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string SundayMenu {
            get {
                return ResourceManager.GetString("SundayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sv-SE.
        /// </summary>
        internal static string Swedish {
            get {
                return ResourceManager.GetString("Swedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svenska.
        /// </summary>
        internal static string SwedishMenu {
            get {
                return ResourceManager.GetString("SwedishMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use large taskbar.
        /// </summary>
        internal static string SwitchToLargeTaskbarButtonsMenu {
            get {
                return ResourceManager.GetString("SwitchToLargeTaskbarButtonsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use small taskbar.
        /// </summary>
        internal static string SwitchToSmallTaskbarButtonsMenu {
            get {
                return ResourceManager.GetString("SwitchToSmallTaskbarButtonsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextContrast.
        /// </summary>
        internal static string TextContrast {
            get {
                return ResourceManager.GetString("TextContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string TextContrast1Menu {
            get {
                return ResourceManager.GetString("TextContrast1Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TextContrast2Menu {
            get {
                return ResourceManager.GetString("TextContrast2Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string TextContrast3Menu {
            get {
                return ResourceManager.GetString("TextContrast3Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string TextContrast4Menu {
            get {
                return ResourceManager.GetString("TextContrast4Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string TextContrast5Menu {
            get {
                return ResourceManager.GetString("TextContrast5Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Contrast.
        /// </summary>
        internal static string TextContrastMenu {
            get {
                return ResourceManager.GetString("TextContrastMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string ThursdayMenu {
            get {
                return ResourceManager.GetString("ThursdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to update the application..
        /// </summary>
        internal static string ToUpdateTheApplication {
            get {
                return ResourceManager.GetString("ToUpdateTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try manually downloading it via a web browser from this address:.
        /// </summary>
        internal static string TryDownloadingManuallyFromThisAddress {
            get {
                return ResourceManager.GetString("TryDownloadingManuallyFromThisAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string TuesdayMenu {
            get {
                return ResourceManager.GetString("TuesdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse.
        /// </summary>
        internal static string UnableToParse {
            get {
                return ResourceManager.GetString("UnableToParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseApplicationLog.
        /// </summary>
        internal static string UseApplicationLog {
            get {
                return ResourceManager.GetString("UseApplicationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use application log.
        /// </summary>
        internal static string UseApplicationLogMenu {
            get {
                return ResourceManager.GetString("UseApplicationLogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseSilentNotifications.
        /// </summary>
        internal static string UseSilentNotifications {
            get {
                return ResourceManager.GetString("UseSilentNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use silent notifications.
        /// </summary>
        internal static string UseSilentNotificationsMenu {
            get {
                return ResourceManager.GetString("UseSilentNotificationsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WednesdayMenu {
            get {
                return ResourceManager.GetString("WednesdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week .
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
