//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekNumber {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeekNumber.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeekNumber by Voltura AB
        ///
        ///https://voltura.github.io/WeekNumber
        ///
        ///Copyright © Voltura AB 2018-2021.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WeekNumber.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundB.
        /// </summary>
        internal static string BackgroundB {
            get {
                return ResourceManager.GetString("BackgroundB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundG.
        /// </summary>
        internal static string BackgroundG {
            get {
                return ResourceManager.GetString("BackgroundG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string BackgroundMenu {
            get {
                return ResourceManager.GetString("BackgroundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundR.
        /// </summary>
        internal static string BackgroundR {
            get {
                return ResourceManager.GetString("BackgroundR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar week rule.
        /// </summary>
        internal static string CalendarRuleMenu {
            get {
                return ResourceManager.GetString("CalendarRuleMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    !   .
        /// </summary>
        internal static string ClearThroat {
            get {
                return ResourceManager.GetString("ClearThroat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon colors.
        /// </summary>
        internal static string ColorsMenu {
            get {
                return ResourceManager.GetString("ColorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit WeekNumber.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update icon resolution..
        /// </summary>
        internal static string FailedToChangeIconResolution {
            get {
                return ResourceManager.GetString("FailedToChangeIconResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set Icon. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToSetIcon {
            get {
                return ResourceManager.GetString("FailedToSetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not calendar week rule setting. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateCalendarWeekRule {
            get {
                return ResourceManager.GetString("FailedToUpdateCalendarWeekRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update color..
        /// </summary>
        internal static string FailedToUpdateColor {
            get {
                return ResourceManager.GetString("FailedToUpdateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update first day of week setting.
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateDayOfWeek {
            get {
                return ResourceManager.GetString("FailedToUpdateDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update registry.
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string FailedToUpdateRegistry {
            get {
                return ResourceManager.GetString("FailedToUpdateRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day.
        /// </summary>
        internal static string FirstDayMenu {
            get {
                return ResourceManager.GetString("FirstDayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day Of Week.
        /// </summary>
        internal static string FirstDayOfWeekMenu {
            get {
                return ResourceManager.GetString("FirstDayOfWeekMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Four Day Week.
        /// </summary>
        internal static string FirstFourDayWeekMenu {
            get {
                return ResourceManager.GetString("FirstFourDayWeekMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Full Week.
        /// </summary>
        internal static string FirstFullWeekMenu {
            get {
                return ResourceManager.GetString("FirstFullWeekMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForceRedraw.
        /// </summary>
        internal static string ForceRedraw {
            get {
                return ResourceManager.GetString("ForceRedraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForegroundB.
        /// </summary>
        internal static string ForegroundB {
            get {
                return ResourceManager.GetString("ForegroundB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForegroundG.
        /// </summary>
        internal static string ForegroundG {
            get {
                return ResourceManager.GetString("ForegroundG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string ForegroundMenu {
            get {
                return ResourceManager.GetString("ForegroundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForegroundR.
        /// </summary>
        internal static string ForegroundR {
            get {
                return ResourceManager.GetString("ForegroundR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string FridayMenu {
            get {
                return ResourceManager.GetString("FridayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128x128.
        /// </summary>
        internal static string Icon128 {
            get {
                return ResourceManager.GetString("Icon128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16x16.
        /// </summary>
        internal static string Icon16 {
            get {
                return ResourceManager.GetString("Icon16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20x20.
        /// </summary>
        internal static string Icon20 {
            get {
                return ResourceManager.GetString("Icon20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24x24.
        /// </summary>
        internal static string Icon24 {
            get {
                return ResourceManager.GetString("Icon24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256x256.
        /// </summary>
        internal static string Icon256 {
            get {
                return ResourceManager.GetString("Icon256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32x32.
        /// </summary>
        internal static string Icon32 {
            get {
                return ResourceManager.GetString("Icon32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40x40.
        /// </summary>
        internal static string Icon40 {
            get {
                return ResourceManager.GetString("Icon40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48x48.
        /// </summary>
        internal static string Icon48 {
            get {
                return ResourceManager.GetString("Icon48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 512x512.
        /// </summary>
        internal static string Icon512 {
            get {
                return ResourceManager.GetString("Icon512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64x64.
        /// </summary>
        internal static string Icon64 {
            get {
                return ResourceManager.GetString("Icon64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconResolution.
        /// </summary>
        internal static string IconResolution {
            get {
                return ResourceManager.GetString("IconResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon resolution.
        /// </summary>
        internal static string IconResolutionMenu {
            get {
                return ResourceManager.GetString("IconResolutionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string MondayMenu {
            get {
                return ResourceManager.GetString("MondayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this function is not implemented yet..
        /// </summary>
        internal static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeekNumber will not start with Windows.
        /// </summary>
        internal static string NotStartWithWindows {
            get {
                return ResourceManager.GetString("NotStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors reset.
        /// </summary>
        internal static string ResetColors {
            get {
                return ResourceManager.GetString("ResetColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset colors.
        /// </summary>
        internal static string ResetColorsMenu {
            get {
                return ResourceManager.GetString("ResetColorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string SaturdayMenu {
            get {
                return ResourceManager.GetString("SaturdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save icon....
        /// </summary>
        internal static string SaveIconMenu {
            get {
                return ResourceManager.GetString("SaveIconMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select background color.
        /// </summary>
        internal static string SelectBackgroundColor {
            get {
                return ResourceManager.GetString("SelectBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select foreground color.
        /// </summary>
        internal static string SelectForegroundColor {
            get {
                return ResourceManager.GetString("SelectForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SeparatorMenu {
            get {
                return ResourceManager.GetString("SeparatorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeekNumber set to start with Windows.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        internal static string StartWithWindowsMenu {
            get {
                return ResourceManager.GetString("StartWithWindowsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string SundayMenu {
            get {
                return ResourceManager.GetString("SundayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string ThursdayMenu {
            get {
                return ResourceManager.GetString("ThursdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string TuesdayMenu {
            get {
                return ResourceManager.GetString("TuesdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. 
        ///
        ///Please report to feedback@voltura.se!.
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string WednesdayMenu {
            get {
                return ResourceManager.GetString("WednesdayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week .
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
